package main.java.de.embl.rieslab.emu.ui.uiproperties.utils;

import main.java.de.embl.rieslab.emu.ui.uiproperties.MultiStateUIProperty;
import main.java.de.embl.rieslab.emu.ui.uiproperties.SingleStateUIProperty;
import main.java.de.embl.rieslab.emu.ui.uiproperties.TwoStateUIProperty;

public class UIPropertyUtils {

	/**
	 * Tests if the string has been generated by a SingelStateUIProperty, a TwoStateUIProperty or a MultiStateUIProperty.
	 * 
	 * @param s String to test, value in the first column of the table
	 * @return True if corresponds to a field value.
	 */
	public static boolean isStateValue(String s){
		if (s.contains(SingleStateUIProperty.getValueName())
				|| s.contains(TwoStateUIProperty.getOnStateName()) 
				|| s.contains(TwoStateUIProperty.getOffStateName())
				|| s.matches(".*"+MultiStateUIProperty.getGenericStateName()+".*")){
			return true;
		}
		return false;
	}
}
